### PR TITLE
Jt1399 test edit

### PR DESCRIPTION
**Pull request by jt1399**
I'm not sure if this is how it works or not. I'm just trying with this one part and want to know if it was done right. I'm not sure since this is my first time working with a translation and even github itself :/

### CODE REVIEW

**Comment by jt1399** [comment]
also, pardon the embarrassing typo of description there :/

**Comment by Lycan911** [comment]
It's Valentia, not Valencia.

**Comment by jt1399** [comment]
fixed

**Comment by jt1399** [comment]
was curious about learning to do text patches but I guess this is dead now, bit of a bummer

**Pull request closed without merging**
